# Generated by Django 3.2.9 on 2024-02-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplitWiseApp', '0003_alter_expense_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='participants',
            field=models.ManyToManyField(related_name='group_expenses', to='SplitWiseApp.User'),
        ),
    ]
