# Generated by Django 3.2.9 on 2024-02-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SplitWiseApp', '0004_auto_20240211_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplitWiseApp.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplitWiseApp.user')),
            ],
        ),
    ]
