# Generated by Django 3.2.9 on 2024-02-12 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SplitWiseApp', '0005_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='participants',
        ),
        migrations.AddField(
            model_name='expense',
            name='participants',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SplitWiseApp.user'),
            preserve_default=False,
        ),
    ]
