# Generated by Django 3.2.9 on 2024-02-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplitWiseApp', '0006_auto_20240212_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
