# Generated by Django 3.2.9 on 2024-02-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplitWiseApp', '0007_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='participants',
        ),
        migrations.AddField(
            model_name='expense',
            name='participants',
            field=models.ManyToManyField(to='SplitWiseApp.User'),
        ),
    ]
