# Generated by Django 3.2.9 on 2024-02-13 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SplitWiseApp', '0008_auto_20240213_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='participants',
        ),
        migrations.AddField(
            model_name='expense',
            name='new_participants',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SplitWiseApp.user'),
        ),
    ]
